import React, { useContext, useState, useEffect } from 'react';
import { LanguageContext } from '../App';
import { dbService } from '../services/dbService';
import { ObservationRecord } from '../types';
import { Printer, FileText, Download } from 'lucide-react';

export default function ReportsModule() {
  const { t } = useContext(LanguageContext);
  const [data, setData] = useState<ObservationRecord[]>([]);

  useEffect(() => {
    dbService.getAllObservations().then(setData);
  }, []);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center print:hidden">
        <h2 className="text-2xl font-bold text-gray-800">{t('reports')}</h2>
        <button 
          onClick={handlePrint}
          className="flex items-center gap-2 bg-gray-900 text-white px-4 py-2 rounded-lg hover:bg-gray-800 transition-colors"
        >
          <Printer size={18} />
          {t('printReport')}
        </button>
      </div>

      <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 print:shadow-none print:border-none print:p-0">
        
        {/* Report Header */}
        <div className="text-center border-b-2 border-green-800 pb-6 mb-8">
          <img src="https://via.placeholder.com/60x60/15803d/ffffff?text=KP" alt="Logo" className="w-16 h-16 mx-auto mb-2 rounded-full" />
          <h1 className="text-xl font-bold uppercase text-gray-900">Elementary & Secondary Education Department</h1>
          <h2 className="text-lg font-medium text-gray-600">Government of Khyber Pakhtunkhwa</h2>
          <div className="mt-4 inline-block px-4 py-1 bg-green-100 text-green-800 text-sm font-bold rounded-full">
            Monthly Compliance Report
          </div>
        </div>

        {/* Report Summary */}
        <div className="grid grid-cols-3 gap-6 mb-8 text-center print:grid-cols-3">
          <div className="p-4 bg-gray-50 rounded-lg print:border print:border-gray-200">
            <p className="text-sm text-gray-500">Total Visits</p>
            <p className="text-2xl font-bold text-gray-900">{data.length}</p>
          </div>
          <div className="p-4 bg-gray-50 rounded-lg print:border print:border-gray-200">
             <p className="text-sm text-gray-500">Avg Compliance Score</p>
             <p className="text-2xl font-bold text-green-700">
               {(data.reduce((acc, c) => acc + c.rating, 0) / (data.length || 1)).toFixed(1)}
             </p>
          </div>
          <div className="p-4 bg-gray-50 rounded-lg print:border print:border-gray-200">
             <p className="text-sm text-gray-500">Mentoring Sessions</p>
             <p className="text-2xl font-bold text-indigo-700">{data.filter(d => d.mentoringNotes).length}</p>
          </div>
        </div>

        {/* Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-gray-600">
            <thead className="bg-green-50 text-green-900 font-bold uppercase text-xs">
              <tr>
                <th className="p-3">Date</th>
                <th className="p-3">Teacher</th>
                <th className="p-3">Subject</th>
                <th className="p-3 text-center">Plan?</th>
                <th className="p-3 text-center">AV?</th>
                <th className="p-3 text-right">Rating</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {data.map(row => (
                <tr key={row.id}>
                  <td className="p-3">{new Date(row.date).toLocaleDateString()}</td>
                  <td className="p-3 font-medium text-gray-900">{row.teacherName}</td>
                  <td className="p-3">{row.subject}</td>
                  <td className="p-3 text-center">{row.indicators.lessonPlan ? 'Yes' : 'No'}</td>
                  <td className="p-3 text-center">{row.indicators.avAids ? 'Yes' : 'No'}</td>
                  <td className="p-3 text-right font-bold">{row.rating}/5</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-gray-200 flex justify-between text-xs text-gray-400">
          <p>Generated by KPK School Leaders Portal</p>
          <p>{new Date().toLocaleString()}</p>
        </div>
      </div>
    </div>
  );
}