import { Language, TranslationKey } from './types';

export const TRANSLATIONS: Record<Language, Record<TranslationKey, string>> = {
  [Language.ENGLISH]: {
    appTitle: 'KPK School Leaders',
    dashboard: 'Dashboard',
    observation: 'Observation',
    feedback: 'Feedback & Support',
    academic: 'Academic Monitoring',
    assessment: 'Assessment & Eval',
    training: 'Prof. Development',
    reports: 'Compliance Reports',
    knowledge: 'Knowledge Hub',
    newObservation: 'New Observation',
    teacherName: 'Teacher Name',
    subject: 'Subject',
    save: 'Save Record',
    cancel: 'Cancel',
    history: 'Recent History',
    lessonPlan: 'Lesson Plan Available?',
    avAids: 'AV Aids Used?',
    engagement: 'Students Engaged?',
    notebooks: 'Notebooks Checked?',
    deficiencies: 'Identified Gaps',
    mentoring: 'Mentoring Provided',
    submitSuccess: 'Record Saved Locally',
    welcome: 'Welcome, School Leader',
    aiAssistant: 'Pedagogy AI Support',
    aiPrompt: 'Ask about teaching strategies or policies...',
    printReport: 'Print / PDF',
    actionPlan: 'Agreed Action Plan',
    followUp: 'Follow-up Date',
    enrollment: 'Total Enrollment',
    attendance: 'Attendance (%)',
    community: 'Community Meeting Held?',
    slo: 'SLO Topic',
    passRate: 'Pass Rate',
    trainingTitle: 'Training Title'
  },
  [Language.URDU]: {
    appTitle: 'کے پی کے سکول لیڈرز',
    dashboard: 'ڈیش بورڈ',
    observation: 'کلاس روم کا مشاہدہ',
    feedback: 'فیڈ بیک اور سپورٹ',
    academic: 'تعلیمی نگرانی',
    assessment: 'تشخیص اور جائزہ',
    training: 'پیشہ ورانہ تربیت',
    reports: 'رپورٹس',
    knowledge: 'معلوماتی مرکز',
    newObservation: 'نیا مشاہدہ',
    teacherName: 'استاد کا نام',
    subject: 'مضمون',
    save: 'محفوظ کریں',
    cancel: 'منسوخ کریں',
    history: 'حالیہ ریکارڈ',
    lessonPlan: 'کیا لیسن پلان موجود ہے؟',
    avAids: 'کیا اے وی ایڈز استعمال ہوئے؟',
    engagement: 'کیا طلباء متوجہ تھے؟',
    notebooks: 'کیا کاپیاں چیک کی گئیں؟',
    deficiencies: 'نشاندہی شدہ کمیاں',
    mentoring: 'فراہمی رہنمائی',
    submitSuccess: 'ریکارڈ محفوظ ہو گیا',
    welcome: 'خوش آمدید، سکول لیڈر',
    aiAssistant: 'تعلیمی معاون (AI)',
    aiPrompt: 'تدریسی حکمت عملی یا پالیسی کے بارے میں پوچھیں...',
    printReport: 'پرنٹ / پی ڈی ایف',
    actionPlan: 'متفقہ ایکشن پلان',
    followUp: 'فالو اپ تاریخ',
    enrollment: 'کل داخلہ',
    attendance: 'حاضری (٪)',
    community: 'کیا کمیونٹی میٹنگ ہوئی؟',
    slo: 'ایس ایل او ٹاپک',
    passRate: 'پاس کی شرح',
    trainingTitle: 'تربیت کا عنوان'
  }
};

export const MOCK_TEACHERS = [
  { id: '1', name: 'Ahmed Khan', designation: 'PST', cnic: '11111-1111111-1' },
  { id: '2', name: 'Fatima Bibi', designation: 'CT', cnic: '22222-2222222-2' },
  { id: '3', name: 'Muhammad Ali', designation: 'AT', cnic: '33333-3333333-3' },
];